const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcrypt');
const { v4: uuidv4 } = require('uuid');

const prisma = new PrismaClient();

const menuItems = [
  // Hot Beverages — Coffee
  { name: 'Espresso', category: 'Coffee', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Doppio', category: 'Coffee', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Lungo', category: 'Coffee', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Americano', category: 'Coffee', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Cortado', category: 'Coffee', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Flat White', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Caffe Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Cappuccino', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Cappuccino Milk', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Affogato', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Mocha Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'White Mocha Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Caramel Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Salted Caramel Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Vanilla Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Spanish Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Coconut Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Chai Tea Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Espresso Macchiato', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Red Eye', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Wild 91 Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Cafe Latte Camel', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced Americano', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Classic Iced Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced Caramel Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced Mocha', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced White Mocha', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced Vanilla Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced Spanish Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced Coconut Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced Chai Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'V60', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced V60', category: 'Coffee', productCategory: 'Hot Beverages', price: 3.00 },
  // Hot Tea
  { name: 'Black Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Green Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Red Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Ginger Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Lemon Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Masala Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Somali Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Fresh 91 Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Lipton Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Lipton Black', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Somali Black', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Xanshar', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Hot Chocolate', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Matcha Latte', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Match Latte', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Karak Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Hibiscus Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Camel Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Camel Qashar', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Dawa Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Daqar Qashar', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Camel Tea Dakhar', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Spanish Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Lipton Camel', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Lipton Maraci', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Somali Tea Maraci', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Somali Maraci With Dakhar', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Sinimon Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: '9 One Special Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Fruit Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 2.50 },
  // Matcha Corner
  { name: 'Ice Matcha Latte', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Dirty Matcha Latte', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Iced Caramel Matcha', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Iced Spanish Matcha', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Iced Vanilla Matcha', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Iced White Chocolate Matcha', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Iced Matcha Refresher', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Ice Coconut Matcha Latte', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Ice Mango Matcha Latte', category: 'Matcha', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Ice Blue Matcha Latte', category: 'Matcha', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Ice Strawberry Matcha Latte', category: 'Matcha', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Blueberry Matcha Latte', category: 'Matcha', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Matcha Frappe', category: 'Matcha', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Matcha Smoothie', category: 'Matcha', productCategory: 'Signature & Specialty', price: 3.50 },
  // Our Signature
  { name: 'Iced 9One Refresher', category: 'Signature', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Iced Mango Refresher', category: 'Signature', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Iced Peach Refresher', category: 'Signature', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Iced Watermelon Refresher', category: 'Signature', productCategory: 'Signature & Specialty', price: 3.00 },
  // Frappes
  { name: 'Coffee Frappe', category: 'Frappes', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Chocolate Frappe', category: 'Frappes', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Caramelo Frappe', category: 'Frappes', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Lotus Frappe', category: 'Frappes', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Strawberry Cream Frappe', category: 'Frappes', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Vanilla Frappe', category: 'Frappes', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Vanilla Lotus Frappe', category: 'Frappes', productCategory: 'Cold Beverages', price: 3.50 },
  // Mojitos
  { name: 'Blueberry Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Green Apple Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Mango Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Passion Fruit Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Pineapple Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Strawberry Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Peach Mango Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Pina Colada Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 3.00 },
  { name: '91 Blue Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Taste The Rainbow', category: 'Mojitos', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Mixed Mojitos', category: 'Mojitos', productCategory: 'Cold Beverages', price: 3.50 },
  // Smoothies
  { name: 'Berries Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Blueberry Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Banana Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Mango Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Pina Colada Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Pineapple Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Raspberry Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Strawberry Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Cocktail Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 4.00 },
  // Fresh Juice
  { name: 'Avocado Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Lemon Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Mango Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Orange Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Papaya Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Strawberry Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Watermelon Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Apple Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Cocktail Fresh Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Cocktail Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Mixed Fruit', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 3.00 },
  // Hibiscus & Iced Tea
  { name: 'Ice Berry Hibiscus', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Peach Iced Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Raspberry Iced Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Blueberry Ice Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Peach Ice Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Raspberry Ice Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Strawberry Ice Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Ice Passion Fruit Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Peach Ice Tea With Lemon', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.80 },
  { name: 'Iced Blueberry Hibiscus', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Iced Passion Fruit Hibiscus', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Ice Hibiscus Mango', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Ice Strawberry Hibiscus', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Lemonada Ice Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 3.00 },
  // Milkshakes
  { name: 'Banana Milkshake', category: 'Milkshakes', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Coffee Milkshake', category: 'Milkshakes', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Lotus Milkshake', category: 'Milkshakes', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Mango Milkshake', category: 'Milkshakes', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Oreo Milkshake', category: 'Milkshakes', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Strawberry Milkshake', category: 'Milkshakes', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Vanilla Milkshake', category: 'Milkshakes', productCategory: 'Cold Beverages', price: 3.00 },
  // Breakfast
  { name: 'Boiled Egg', category: 'Breakfast', productCategory: 'Food', price: 3.00 },
  { name: 'Egg Canjelo', category: 'Breakfast', productCategory: 'Food', price: 3.50 },
  { name: 'Canjelo With Honey', category: 'Breakfast', productCategory: 'Food', price: 3.00 },
  { name: 'Spanish Omelette', category: 'Breakfast', productCategory: 'Food', price: 3.50 },
  { name: 'Faasuliyad', category: 'Breakfast', productCategory: 'Food', price: 3.50 },
  { name: 'Malawax With Honey & Banana', category: 'Breakfast', productCategory: 'Food', price: 3.50 },
  { name: 'French Toast', category: 'Breakfast', productCategory: 'Food', price: 4.00 },
  { name: 'Oatmeal Bowl', category: 'Breakfast', productCategory: 'Food', price: 4.00 },
  { name: 'Pancakes Stack', category: 'Breakfast', productCategory: 'Food', price: 4.00 },
  { name: 'Shokoshoko', category: 'Breakfast', productCategory: 'Food', price: 4.00 },
  { name: 'Cambaabur', category: 'Breakfast', productCategory: 'Food', price: 4.00 },
  { name: 'Cheese Omelet', category: 'Breakfast', productCategory: 'Food', price: 4.00 },
  { name: 'Suqaar', category: 'Breakfast', productCategory: 'Food', price: 4.00 },
  { name: 'Egg Sandwich', category: 'Breakfast', productCategory: 'Food', price: 4.50 },
  { name: 'Grilled Chicken Fish', category: 'Breakfast', productCategory: 'Food', price: 4.50 },
  { name: 'Mutton Liver Fry', category: 'Breakfast', productCategory: 'Food', price: 4.50 },
  { name: 'Waffles', category: 'Breakfast', productCategory: 'Food', price: 4.50 },
  { name: 'Beergeel', category: 'Breakfast', productCategory: 'Food', price: 5.00 },
  { name: 'Chicken Toast', category: 'Breakfast', productCategory: 'Food', price: 5.50 },
  { name: 'Waffle Chocolate', category: 'Breakfast', productCategory: 'Food', price: 5.00 },
  { name: 'Waffle Lotus', category: 'Breakfast', productCategory: 'Food', price: 5.00 },
  { name: 'Continental Breakfast', category: 'Breakfast', productCategory: 'Food', price: 7.00 },
  { name: 'Liver Zeko', category: 'Breakfast', productCategory: 'Food', price: 6.00 },
  // Burgers
  { name: 'Burger Tuna', category: 'Burgers', productCategory: 'Food', price: 4.00 },
  { name: 'Fish Burger', category: 'Burgers', productCategory: 'Food', price: 4.50 },
  { name: 'Grilled Chicken Burger', category: 'Burgers', productCategory: 'Food', price: 4.50 },
  { name: 'Smash Burger', category: 'Burgers', productCategory: 'Food', price: 5.00 },
  { name: 'Stacker Burger', category: 'Burgers', productCategory: 'Food', price: 5.00 },
  { name: 'BBQ Chicken Burger', category: 'Burgers', productCategory: 'Food', price: 6.00 },
  { name: 'Double Smash Burger', category: 'Burgers', productCategory: 'Food', price: 7.50 },
  // Pizza
  { name: 'Chicken Pizza Small', category: 'Pizza', productCategory: 'Food', price: 5.00 },
  { name: 'Fish Pizza Small', category: 'Pizza', productCategory: 'Food', price: 5.00 },
  { name: 'Hawaiian Pizza Small', category: 'Pizza', productCategory: 'Food', price: 5.00 },
  { name: 'Margherita Pizza Small', category: 'Pizza', productCategory: 'Food', price: 5.00 },
  { name: 'Tuna Pizza Small', category: 'Pizza', productCategory: 'Food', price: 5.00 },
  { name: 'Meat Pizza Small', category: 'Pizza', productCategory: 'Food', price: 6.00 },
  { name: 'Chicken Pizza Medium', category: 'Pizza', productCategory: 'Food', price: 8.00 },
  { name: 'Fish Pizza Medium', category: 'Pizza', productCategory: 'Food', price: 8.00 },
  { name: 'Hawaiian Pizza Medium', category: 'Pizza', productCategory: 'Food', price: 8.00 },
  { name: 'Margherita Pizza Medium', category: 'Pizza', productCategory: 'Food', price: 8.00 },
  { name: 'Tuna Pizza Medium', category: 'Pizza', productCategory: 'Food', price: 8.00 },
  { name: 'Meat Pizza Medium', category: 'Pizza', productCategory: 'Food', price: 9.00 },
  { name: 'Chicken Pizza Large', category: 'Pizza', productCategory: 'Food', price: 10.00 },
  { name: 'Fish Pizza Large', category: 'Pizza', productCategory: 'Food', price: 10.00 },
  { name: 'Hawaiian Pizza Large', category: 'Pizza', productCategory: 'Food', price: 10.00 },
  { name: 'Margherita Pizza Large', category: 'Pizza', productCategory: 'Food', price: 10.00 },
  { name: 'Tuna Pizza Large', category: 'Pizza', productCategory: 'Food', price: 10.00 },
  { name: 'Meat Pizza Large', category: 'Pizza', productCategory: 'Food', price: 12.00 },
  { name: '9One Pizza', category: 'Pizza', productCategory: 'Food', price: 15.00 },
  // Pasta
  { name: 'Pasta Bolognese', category: 'Pasta', productCategory: 'Food', price: 5.00 },
  { name: 'Pasta Alfredo', category: 'Pasta', productCategory: 'Food', price: 5.50 },
  { name: '9One Pasta', category: 'Pasta', productCategory: 'Food', price: 6.50 },
  { name: 'Spaghetti Matriciana', category: 'Pasta', productCategory: 'Food', price: 7.00 },
  // Main Course
  { name: 'Sanbuuse', category: 'Main Course', productCategory: 'Food', price: 0.70 },
  { name: 'Rice', category: 'Main Course', productCategory: 'Food', price: 2.00 },
  { name: 'Package Afura', category: 'Main Course', productCategory: 'Food', price: 6.00 },
  { name: 'Fish Curry', category: 'Main Course', productCategory: 'Food', price: 7.00 },
  { name: 'Chicken Curry', category: 'Main Course', productCategory: 'Food', price: 7.00 },
  { name: 'Chicken Curry With Chapati', category: 'Main Course', productCategory: 'Food', price: 7.00 },
  { name: 'Chicken Mionase', category: 'Main Course', productCategory: 'Food', price: 7.00 },
  { name: 'Beef Curry', category: 'Main Course', productCategory: 'Food', price: 7.50 },
  { name: 'Butter Chicken', category: 'Main Course', productCategory: 'Food', price: 7.50 },
  { name: 'Biryani Fish', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Biryani Meat', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Chicken Biryani', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Finger Chicken', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Finger Fish', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Goat Meat-Falfal', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Grilled Chicken Breast', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Grilled Fish', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Roos Beef', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Roos Chicken', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Sweet And Sour Fish', category: 'Main Course', productCategory: 'Food', price: 9.00 },
  { name: 'Stacke Beef', category: 'Main Course', productCategory: 'Food', price: 9.00 },
  { name: 'Somali Goat Hanid', category: 'Main Course', productCategory: 'Food', price: 10.00 },
  // Salads
  { name: 'Avocado Egg Salad', category: 'Salads', productCategory: 'Food', price: 3.00 },
  { name: 'Beetroot & Carrot Salad', category: 'Salads', productCategory: 'Food', price: 3.00 },
  { name: 'Fruit Salad', category: 'Salads', productCategory: 'Food', price: 3.00 },
  { name: 'Green Garden Salad', category: 'Salads', productCategory: 'Food', price: 3.00 },
  { name: 'Spinach Salad', category: 'Salads', productCategory: 'Food', price: 3.50 },
  { name: 'Tuna Light Salad', category: 'Salads', productCategory: 'Food', price: 3.50 },
  { name: 'Chicken Salad', category: 'Salads', productCategory: 'Food', price: 4.00 },
  { name: 'Fish Salad', category: 'Salads', productCategory: 'Food', price: 4.00 },
  // Sandwiches & Wraps
  { name: 'Chicken Wrap', category: 'Sandwiches', productCategory: 'Food', price: 6.00 },
  { name: 'Fish Wrap', category: 'Sandwiches', productCategory: 'Food', price: 6.00 },
  { name: 'Meat Wrap', category: 'Sandwiches', productCategory: 'Food', price: 6.00 },
  { name: 'Shawarma Chicken', category: 'Sandwiches', productCategory: 'Food', price: 6.00 },
  { name: 'Shawarma Fish', category: 'Sandwiches', productCategory: 'Food', price: 6.00 },
  { name: '9One Sandwich', category: 'Sandwiches', productCategory: 'Food', price: 6.50 },
  { name: 'Beef Enchiladas', category: 'Sandwiches', productCategory: 'Food', price: 6.50 },
  { name: 'Sandwich Fish', category: 'Sandwiches', productCategory: 'Food', price: 6.50 },
  { name: 'Sandwich Meat', category: 'Sandwiches', productCategory: 'Food', price: 6.50 },
  // Soups
  { name: 'Creamy Vegetable Soup', category: 'Soups', productCategory: 'Food', price: 3.00 },
  { name: 'Lentil Soup', category: 'Soups', productCategory: 'Food', price: 3.00 },
  { name: 'Tomato Basil Soup', category: 'Soups', productCategory: 'Food', price: 3.00 },
  { name: 'Chicken Soup', category: 'Soups', productCategory: 'Food', price: 3.50 },
  { name: 'Clear Essence Of Fish Broth', category: 'Soups', productCategory: 'Food', price: 3.50 },
  { name: 'Fish Soup', category: 'Soups', productCategory: 'Food', price: 3.50 },
  { name: 'Mushroom Soup', category: 'Soups', productCategory: 'Food', price: 3.50 },
  // Sides & Sauces
  { name: 'Attack Sauce', category: 'Sides', productCategory: 'Food', price: 0.50 },
  { name: 'BBQ Sauce', category: 'Sides', productCategory: 'Food', price: 0.50 },
  { name: 'Buffalo Infused Sauce', category: 'Sides', productCategory: 'Food', price: 0.50 },
  { name: 'Chilli Sauce', category: 'Sides', productCategory: 'Food', price: 0.50 },
  { name: 'Extra Cheese', category: 'Sides', productCategory: 'Food', price: 0.50 },
  { name: 'Mayonnaise', category: 'Sides', productCategory: 'Food', price: 0.50 },
  { name: 'Chapati', category: 'Sides', productCategory: 'Food', price: 1.00 },
  { name: 'Jappati', category: 'Sides', productCategory: 'Food', price: 1.50 },
  { name: 'French Fries', category: 'Sides', productCategory: 'Food', price: 3.00 },
  { name: 'Cheesy Fries', category: 'Sides', productCategory: 'Food', price: 4.50 },
  { name: 'Chips Masala', category: 'Sides', productCategory: 'Food', price: 5.00 },
  // Bakery & Desserts
  { name: 'Croissant', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 1.20 },
  { name: 'Cookies', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 1.60 },
  { name: 'Donat', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 1.50 },
  { name: 'Hazelnut Cookies', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 1.50 },
  { name: 'Sweetball Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 2.00 },
  { name: 'Cinnamon Roll', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 2.00 },
  { name: 'Almond Croissant', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 2.20 },
  { name: 'Date Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 2.50 },
  { name: 'Toffy Delight', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 2.50 },
  { name: 'Basbusa', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Brownies', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Caramel', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Choco Mirror Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Coconut Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Cream Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Tramisu', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Black Forest Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Caramel Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Cheese Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Chocolate Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Mocha Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Red Velvet', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Basbusa With Pastio', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.30 },
  { name: 'Lotus Cheese Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.50 },
  { name: 'Plate Of Basbusa', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 26.50 },
];

async function main() {
  console.log('Seeding database...');

  await prisma.menuItem.deleteMany();
  await prisma.stampEvent.deleteMany();
  await prisma.staff.deleteMany();

  await prisma.menuItem.createMany({
    data: menuItems.map(item => ({
      id: uuidv4(),
      name: item.name,
      category: item.category,
      productCategory: item.productCategory,
      price: item.price,
      isAvailable: true,
    })),
  });
  console.log(`Seeded ${menuItems.length} menu items`);

  const adminHash = await bcrypt.hash('admin123', 12);
  const staffHash = await bcrypt.hash('staff123', 12);

  await prisma.staff.create({
    data: {
      id: uuidv4(),
      name: 'Admin',
      username: 'admin',
      passwordHash: adminHash,
      role: 'admin',
      isActive: true,
    },
  });

  await prisma.staff.create({
    data: {
      id: uuidv4(),
      name: 'Staff One',
      username: 'staff1',
      passwordHash: staffHash,
      role: 'staff',
      isActive: true,
    },
  });

  console.log('Seeded staff accounts (admin / staff1)');
  console.log('Done!');
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
