const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcrypt');
const { v4: uuidv4 } = require('uuid');

const prisma = new PrismaClient();

const U = id => `https://images.unsplash.com/photo-${id}?w=600&q=80&auto=format&fit=crop`;

// Order matters — first match wins. Specific names → keywords → category fallback.
const IMAGE_RULES = [
  // Specific drinks
  [/affogato/i,                       U('1577805947697-89e18249d767')],
  [/espresso macchiato|macchiato/i,   U('1485808191679-5f86510681a2')],
  [/iced (caramel )?mocha|iced white mocha/i, U('1517701604599-bb29b565090c')],
  [/iced (caramel|vanilla|spanish|coconut|chai|classic )?latte|iced coffee/i, U('1517959105821-eaf2591984ca')],
  [/iced americano/i,                 U('1497935586351-b67a49e012bf')],
  [/iced (.*)?(matcha)/i,             U('1571805129764-d49d22acd5a5')],
  [/(white )?mocha/i,                 U('1578374173705-969cbe6f2d6b')],
  [/cappuccino/i,                     U('1572286258217-215cf8e9d3a4')],
  [/flat white/i,                     U('1494314671902-399b18174975')],
  [/cortado/i,                        U('1559056199-641a0ac8b55e')],
  [/americano/i,                      U('1497935586351-b67a49e012bf')],
  [/(caramel|vanilla|spanish|coconut|salted|wild|camel) latte|latte/i, U('1561882468-9110e03e0f78')],
  [/chai tea latte|chai/i,            U('1592318011281-2b4ade4b69d1')],
  [/doppio|lungo|red eye|v60/i,       U('1510591509098-f4fdc6d0ff04')],
  [/espresso/i,                       U('1510707577719-ae7c14805e3a')],
  [/matcha/i,                         U('1571805129764-d49d22acd5a5')],
  [/hot chocolate/i,                  U('1542990253-0d0f5be5f0ed')],
  [/karak|masala|spanish tea|sinimon|cinnamon/i, U('1592318011281-2b4ade4b69d1')],
  [/hibiscus|fruit tea/i,             U('1565020477847-30d0fb4ef8d2')],
  [/ginger tea/i,                     U('1594631252845-29fc4cc8cde9')],
  [/lemon tea/i,                      U('1556679343-c7306c1976bc')],
  [/green tea/i,                      U('1556679343-c7306c1976bc')],
  [/black tea|lipton|somali|red tea|xanshar|9 one special tea|fresh 91/i, U('1576092768241-dec231879fc3')],
  // Cold drinks
  [/frappe/i,                         U('1572490122747-3968b75cc699')],
  [/smoothie/i,                       U('1525385133512-2f3bdd039054')],
  [/mojito/i,                         U('1551538827-9c037cb4f32a')],
  [/milkshake/i,                      U('1572490122747-3968b75cc699')],
  [/(fresh )?juice|orange|apple|carrot|pineapple/i, U('1600271886742-f049cd451bba')],
  [/refresher/i,                      U('1546173159-315724a31696')],
  [/mango/i,                          U('1605027990121-cbae9e0642db')],
  [/strawberry/i,                     U('1587735243615-c03f25aaff15')],
  [/watermelon/i,                     U('1571575173700-afb9492e6a50')],
  [/peach/i,                          U('1587735243615-c03f25aaff15')],
  [/iced tea/i,                       U('1556679343-c7306c1976bc')],
  // Food
  [/burger/i,                         U('1568901346375-23c9450c58cd')],
  [/pizza/i,                          U('1565299624946-b28f40a0ae38')],
  [/pasta|spaghetti|fettuccine|penne|lasagna/i, U('1551183053-bf91a1d81141')],
  [/salad/i,                          U('1512621776951-a57141f2eefd')],
  [/club sandwich|sandwich/i,         U('1528735602780-2552fd46c7af')],
  [/soup/i,                           U('1547592180-85f173990554')],
  [/omelette|omelet|scrambled|eggs/i, U('1612240498936-65f5101365d2')],
  [/pancake/i,                        U('1528207776546-365bb710ee93')],
  [/waffle/i,                         U('1572569511254-d8f925fe2cbb')],
  [/croissant/i,                      U('1555507036-ab1f4038808a')],
  [/cheesecake|cheese cake|red velvet|basbusa|dessert|cake/i, U('1551024506-0bccd828d307')],
  [/chicken/i,                        U('1604908176997-125f25cc6f3d')],
  [/fries|chips/i,                    U('1573080496219-bb080dd4f877')],
  [/wrap|shawarma/i,                  U('1565299585323-38d6b0865b47')],
  [/rice|biryani/i,                   U('1603133872878-684f208fb84b')],
  [/breakfast|toast|bagel|porridge/i, U('1525351484163-7529414344d8')],
  // Category fallbacks
  [/(coffee|caffe|cafe)/i,            U('1510707577719-ae7c14805e3a')],
  [/tea/i,                            U('1576092768241-dec231879fc3')],
];

const CATEGORY_FALLBACK = {
  Coffee:       U('1510707577719-ae7c14805e3a'),
  'Hot Tea':    U('1576092768241-dec231879fc3'),
  Matcha:       U('1571805129764-d49d22acd5a5'),
  Signature:    U('1546173159-315724a31696'),
  Frappes:      U('1572490122747-3968b75cc699'),
  Mojitos:      U('1551538827-9c037cb4f32a'),
  Smoothies:    U('1525385133512-2f3bdd039054'),
  'Fresh Juice':U('1600271886742-f049cd451bba'),
  'Iced Tea':   U('1556679343-c7306c1976bc'),
  Milkshakes:   U('1572490122747-3968b75cc699'),
  Breakfast:    U('1525351484163-7529414344d8'),
  Burgers:      U('1568901346375-23c9450c58cd'),
  Pizza:        U('1565299624946-b28f40a0ae38'),
  Pasta:        U('1551183053-bf91a1d81141'),
  'Main Course':U('1604908176997-125f25cc6f3d'),
  Salads:       U('1512621776951-a57141f2eefd'),
  Sandwiches:   U('1528735602780-2552fd46c7af'),
  Soups:        U('1547592180-85f173990554'),
  Sides:        U('1573080496219-bb080dd4f877'),
  Desserts:     U('1551024506-0bccd828d307'),
};

function pickImage(name, category) {
  for (const [pattern, url] of IMAGE_RULES) {
    if (pattern.test(name)) return url;
  }
  return CATEGORY_FALLBACK[category] || null;
}

const menuItems = [
  // Hot Beverages — Coffee
  { name: 'Espresso', category: 'Coffee', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Doppio', category: 'Coffee', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Lungo', category: 'Coffee', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Americano', category: 'Coffee', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Cortado', category: 'Coffee', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Flat White', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Caffe Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Cappuccino', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Cappuccino Milk', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Affogato', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Mocha Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'White Mocha Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Caramel Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Salted Caramel Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Vanilla Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Spanish Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Coconut Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Chai Tea Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Espresso Macchiato', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Red Eye', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Wild 91 Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Cafe Latte Camel', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced Americano', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Classic Iced Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced Caramel Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced Mocha', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced White Mocha', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced Vanilla Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced Spanish Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced Coconut Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced Chai Latte', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'V60', category: 'Coffee', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Iced V60', category: 'Coffee', productCategory: 'Hot Beverages', price: 3.00 },
  // Hot Tea
  { name: 'Black Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Green Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Red Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Ginger Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Lemon Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Masala Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Somali Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Fresh 91 Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Lipton Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Lipton Black', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Somali Black', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Xanshar', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.00 },
  { name: 'Hot Chocolate', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Matcha Latte', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Match Latte', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 2.00 },
  { name: 'Karak Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Hibiscus Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Camel Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Camel Qashar', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Dawa Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Daqar Qashar', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Camel Tea Dakhar', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Spanish Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Lipton Camel', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Lipton Maraci', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Somali Tea Maraci', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Somali Maraci With Dakhar', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: 'Sinimon Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 1.50 },
  { name: '9 One Special Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 2.50 },
  { name: 'Fruit Tea', category: 'Hot Tea', productCategory: 'Hot Beverages', price: 2.50 },
  // Matcha Corner
  { name: 'Ice Matcha Latte', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Dirty Matcha Latte', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Iced Caramel Matcha', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Iced Spanish Matcha', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Iced Vanilla Matcha', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Iced White Chocolate Matcha', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Iced Matcha Refresher', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Ice Coconut Matcha Latte', category: 'Matcha', productCategory: 'Signature & Specialty', price: 2.50 },
  { name: 'Ice Mango Matcha Latte', category: 'Matcha', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Ice Blue Matcha Latte', category: 'Matcha', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Ice Strawberry Matcha Latte', category: 'Matcha', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Blueberry Matcha Latte', category: 'Matcha', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Matcha Frappe', category: 'Matcha', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Matcha Smoothie', category: 'Matcha', productCategory: 'Signature & Specialty', price: 3.50 },
  // Our Signature
  { name: 'Iced 9One Refresher', category: 'Signature', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Iced Mango Refresher', category: 'Signature', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Iced Peach Refresher', category: 'Signature', productCategory: 'Signature & Specialty', price: 3.00 },
  { name: 'Iced Watermelon Refresher', category: 'Signature', productCategory: 'Signature & Specialty', price: 3.00 },
  // Frappes
  { name: 'Coffee Frappe', category: 'Frappes', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Chocolate Frappe', category: 'Frappes', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Caramelo Frappe', category: 'Frappes', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Lotus Frappe', category: 'Frappes', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Strawberry Cream Frappe', category: 'Frappes', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Vanilla Frappe', category: 'Frappes', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Vanilla Lotus Frappe', category: 'Frappes', productCategory: 'Cold Beverages', price: 3.50 },
  // Mojitos
  { name: 'Blueberry Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Green Apple Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Mango Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Passion Fruit Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Pineapple Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Strawberry Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Peach Mango Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Pina Colada Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 3.00 },
  { name: '91 Blue Mojito', category: 'Mojitos', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Taste The Rainbow', category: 'Mojitos', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Mixed Mojitos', category: 'Mojitos', productCategory: 'Cold Beverages', price: 3.50 },
  // Smoothies
  { name: 'Berries Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Blueberry Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Banana Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Mango Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Pina Colada Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Pineapple Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Raspberry Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Strawberry Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 3.50 },
  { name: 'Cocktail Smoothie', category: 'Smoothies', productCategory: 'Cold Beverages', price: 4.00 },
  // Fresh Juice
  { name: 'Avocado Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Lemon Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Mango Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Orange Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Papaya Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Strawberry Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Watermelon Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Apple Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Cocktail Fresh Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Cocktail Juice', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Mixed Fruit', category: 'Fresh Juice', productCategory: 'Cold Beverages', price: 3.00 },
  // Hibiscus & Iced Tea
  { name: 'Ice Berry Hibiscus', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Peach Iced Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Raspberry Iced Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Blueberry Ice Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Peach Ice Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Raspberry Ice Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Strawberry Ice Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Ice Passion Fruit Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.50 },
  { name: 'Peach Ice Tea With Lemon', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 2.80 },
  { name: 'Iced Blueberry Hibiscus', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Iced Passion Fruit Hibiscus', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Ice Hibiscus Mango', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Ice Strawberry Hibiscus', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Lemonada Ice Tea', category: 'Iced Tea', productCategory: 'Cold Beverages', price: 3.00 },
  // Milkshakes
  { name: 'Banana Milkshake', category: 'Milkshakes', productCategory: 'Cold Beverages', price: 2.00 },
  { name: 'Coffee Milkshake', category: 'Milkshakes', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Lotus Milkshake', category: 'Milkshakes', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Mango Milkshake', category: 'Milkshakes', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Oreo Milkshake', category: 'Milkshakes', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Strawberry Milkshake', category: 'Milkshakes', productCategory: 'Cold Beverages', price: 3.00 },
  { name: 'Vanilla Milkshake', category: 'Milkshakes', productCategory: 'Cold Beverages', price: 3.00 },
  // Breakfast
  { name: 'Boiled Egg', category: 'Breakfast', productCategory: 'Food', price: 3.00 },
  { name: 'Egg Canjelo', category: 'Breakfast', productCategory: 'Food', price: 3.50 },
  { name: 'Canjelo With Honey', category: 'Breakfast', productCategory: 'Food', price: 3.00 },
  { name: 'Spanish Omelette', category: 'Breakfast', productCategory: 'Food', price: 3.50 },
  { name: 'Faasuliyad', category: 'Breakfast', productCategory: 'Food', price: 3.50 },
  { name: 'Malawax With Honey & Banana', category: 'Breakfast', productCategory: 'Food', price: 3.50 },
  { name: 'French Toast', category: 'Breakfast', productCategory: 'Food', price: 4.00 },
  { name: 'Oatmeal Bowl', category: 'Breakfast', productCategory: 'Food', price: 4.00 },
  { name: 'Pancakes Stack', category: 'Breakfast', productCategory: 'Food', price: 4.00 },
  { name: 'Shokoshoko', category: 'Breakfast', productCategory: 'Food', price: 4.00 },
  { name: 'Cambaabur', category: 'Breakfast', productCategory: 'Food', price: 4.00 },
  { name: 'Cheese Omelet', category: 'Breakfast', productCategory: 'Food', price: 4.00 },
  { name: 'Suqaar', category: 'Breakfast', productCategory: 'Food', price: 4.00 },
  { name: 'Egg Sandwich', category: 'Breakfast', productCategory: 'Food', price: 4.50 },
  { name: 'Grilled Chicken Fish', category: 'Breakfast', productCategory: 'Food', price: 4.50 },
  { name: 'Mutton Liver Fry', category: 'Breakfast', productCategory: 'Food', price: 4.50 },
  { name: 'Waffles', category: 'Breakfast', productCategory: 'Food', price: 4.50 },
  { name: 'Beergeel', category: 'Breakfast', productCategory: 'Food', price: 5.00 },
  { name: 'Chicken Toast', category: 'Breakfast', productCategory: 'Food', price: 5.50 },
  { name: 'Waffle Chocolate', category: 'Breakfast', productCategory: 'Food', price: 5.00 },
  { name: 'Waffle Lotus', category: 'Breakfast', productCategory: 'Food', price: 5.00 },
  { name: 'Continental Breakfast', category: 'Breakfast', productCategory: 'Food', price: 7.00 },
  { name: 'Liver Zeko', category: 'Breakfast', productCategory: 'Food', price: 6.00 },
  // Burgers
  { name: 'Burger Tuna', category: 'Burgers', productCategory: 'Food', price: 4.00 },
  { name: 'Fish Burger', category: 'Burgers', productCategory: 'Food', price: 4.50 },
  { name: 'Grilled Chicken Burger', category: 'Burgers', productCategory: 'Food', price: 4.50 },
  { name: 'Smash Burger', category: 'Burgers', productCategory: 'Food', price: 5.00 },
  { name: 'Stacker Burger', category: 'Burgers', productCategory: 'Food', price: 5.00 },
  { name: 'BBQ Chicken Burger', category: 'Burgers', productCategory: 'Food', price: 6.00 },
  { name: 'Double Smash Burger', category: 'Burgers', productCategory: 'Food', price: 7.50 },
  // Pizza
  { name: 'Chicken Pizza Small', category: 'Pizza', productCategory: 'Food', price: 5.00 },
  { name: 'Fish Pizza Small', category: 'Pizza', productCategory: 'Food', price: 5.00 },
  { name: 'Hawaiian Pizza Small', category: 'Pizza', productCategory: 'Food', price: 5.00 },
  { name: 'Margherita Pizza Small', category: 'Pizza', productCategory: 'Food', price: 5.00 },
  { name: 'Tuna Pizza Small', category: 'Pizza', productCategory: 'Food', price: 5.00 },
  { name: 'Meat Pizza Small', category: 'Pizza', productCategory: 'Food', price: 6.00 },
  { name: 'Chicken Pizza Medium', category: 'Pizza', productCategory: 'Food', price: 8.00 },
  { name: 'Fish Pizza Medium', category: 'Pizza', productCategory: 'Food', price: 8.00 },
  { name: 'Hawaiian Pizza Medium', category: 'Pizza', productCategory: 'Food', price: 8.00 },
  { name: 'Margherita Pizza Medium', category: 'Pizza', productCategory: 'Food', price: 8.00 },
  { name: 'Tuna Pizza Medium', category: 'Pizza', productCategory: 'Food', price: 8.00 },
  { name: 'Meat Pizza Medium', category: 'Pizza', productCategory: 'Food', price: 9.00 },
  { name: 'Chicken Pizza Large', category: 'Pizza', productCategory: 'Food', price: 10.00 },
  { name: 'Fish Pizza Large', category: 'Pizza', productCategory: 'Food', price: 10.00 },
  { name: 'Hawaiian Pizza Large', category: 'Pizza', productCategory: 'Food', price: 10.00 },
  { name: 'Margherita Pizza Large', category: 'Pizza', productCategory: 'Food', price: 10.00 },
  { name: 'Tuna Pizza Large', category: 'Pizza', productCategory: 'Food', price: 10.00 },
  { name: 'Meat Pizza Large', category: 'Pizza', productCategory: 'Food', price: 12.00 },
  { name: '9One Pizza', category: 'Pizza', productCategory: 'Food', price: 15.00 },
  // Pasta
  { name: 'Pasta Bolognese', category: 'Pasta', productCategory: 'Food', price: 5.00 },
  { name: 'Pasta Alfredo', category: 'Pasta', productCategory: 'Food', price: 5.50 },
  { name: '9One Pasta', category: 'Pasta', productCategory: 'Food', price: 6.50 },
  { name: 'Spaghetti Matriciana', category: 'Pasta', productCategory: 'Food', price: 7.00 },
  // Main Course
  { name: 'Sanbuuse', category: 'Main Course', productCategory: 'Food', price: 0.70 },
  { name: 'Rice', category: 'Main Course', productCategory: 'Food', price: 2.00 },
  { name: 'Package Afura', category: 'Main Course', productCategory: 'Food', price: 6.00 },
  { name: 'Fish Curry', category: 'Main Course', productCategory: 'Food', price: 7.00 },
  { name: 'Chicken Curry', category: 'Main Course', productCategory: 'Food', price: 7.00 },
  { name: 'Chicken Curry With Chapati', category: 'Main Course', productCategory: 'Food', price: 7.00 },
  { name: 'Chicken Mionase', category: 'Main Course', productCategory: 'Food', price: 7.00 },
  { name: 'Beef Curry', category: 'Main Course', productCategory: 'Food', price: 7.50 },
  { name: 'Butter Chicken', category: 'Main Course', productCategory: 'Food', price: 7.50 },
  { name: 'Biryani Fish', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Biryani Meat', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Chicken Biryani', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Finger Chicken', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Finger Fish', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Goat Meat-Falfal', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Grilled Chicken Breast', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Grilled Fish', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Roos Beef', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Roos Chicken', category: 'Main Course', productCategory: 'Food', price: 8.00 },
  { name: 'Sweet And Sour Fish', category: 'Main Course', productCategory: 'Food', price: 9.00 },
  { name: 'Stacke Beef', category: 'Main Course', productCategory: 'Food', price: 9.00 },
  { name: 'Somali Goat Hanid', category: 'Main Course', productCategory: 'Food', price: 10.00 },
  // Salads
  { name: 'Avocado Egg Salad', category: 'Salads', productCategory: 'Food', price: 3.00 },
  { name: 'Beetroot & Carrot Salad', category: 'Salads', productCategory: 'Food', price: 3.00 },
  { name: 'Fruit Salad', category: 'Salads', productCategory: 'Food', price: 3.00 },
  { name: 'Green Garden Salad', category: 'Salads', productCategory: 'Food', price: 3.00 },
  { name: 'Spinach Salad', category: 'Salads', productCategory: 'Food', price: 3.50 },
  { name: 'Tuna Light Salad', category: 'Salads', productCategory: 'Food', price: 3.50 },
  { name: 'Chicken Salad', category: 'Salads', productCategory: 'Food', price: 4.00 },
  { name: 'Fish Salad', category: 'Salads', productCategory: 'Food', price: 4.00 },
  // Sandwiches & Wraps
  { name: 'Chicken Wrap', category: 'Sandwiches', productCategory: 'Food', price: 6.00 },
  { name: 'Fish Wrap', category: 'Sandwiches', productCategory: 'Food', price: 6.00 },
  { name: 'Meat Wrap', category: 'Sandwiches', productCategory: 'Food', price: 6.00 },
  { name: 'Shawarma Chicken', category: 'Sandwiches', productCategory: 'Food', price: 6.00 },
  { name: 'Shawarma Fish', category: 'Sandwiches', productCategory: 'Food', price: 6.00 },
  { name: '9One Sandwich', category: 'Sandwiches', productCategory: 'Food', price: 6.50 },
  { name: 'Beef Enchiladas', category: 'Sandwiches', productCategory: 'Food', price: 6.50 },
  { name: 'Sandwich Fish', category: 'Sandwiches', productCategory: 'Food', price: 6.50 },
  { name: 'Sandwich Meat', category: 'Sandwiches', productCategory: 'Food', price: 6.50 },
  // Soups
  { name: 'Creamy Vegetable Soup', category: 'Soups', productCategory: 'Food', price: 3.00 },
  { name: 'Lentil Soup', category: 'Soups', productCategory: 'Food', price: 3.00 },
  { name: 'Tomato Basil Soup', category: 'Soups', productCategory: 'Food', price: 3.00 },
  { name: 'Chicken Soup', category: 'Soups', productCategory: 'Food', price: 3.50 },
  { name: 'Clear Essence Of Fish Broth', category: 'Soups', productCategory: 'Food', price: 3.50 },
  { name: 'Fish Soup', category: 'Soups', productCategory: 'Food', price: 3.50 },
  { name: 'Mushroom Soup', category: 'Soups', productCategory: 'Food', price: 3.50 },
  // Sides & Sauces
  { name: 'Attack Sauce', category: 'Sides', productCategory: 'Food', price: 0.50 },
  { name: 'BBQ Sauce', category: 'Sides', productCategory: 'Food', price: 0.50 },
  { name: 'Buffalo Infused Sauce', category: 'Sides', productCategory: 'Food', price: 0.50 },
  { name: 'Chilli Sauce', category: 'Sides', productCategory: 'Food', price: 0.50 },
  { name: 'Extra Cheese', category: 'Sides', productCategory: 'Food', price: 0.50 },
  { name: 'Mayonnaise', category: 'Sides', productCategory: 'Food', price: 0.50 },
  { name: 'Chapati', category: 'Sides', productCategory: 'Food', price: 1.00 },
  { name: 'Jappati', category: 'Sides', productCategory: 'Food', price: 1.50 },
  { name: 'French Fries', category: 'Sides', productCategory: 'Food', price: 3.00 },
  { name: 'Cheesy Fries', category: 'Sides', productCategory: 'Food', price: 4.50 },
  { name: 'Chips Masala', category: 'Sides', productCategory: 'Food', price: 5.00 },
  // Bakery & Desserts
  { name: 'Croissant', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 1.20 },
  { name: 'Cookies', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 1.60 },
  { name: 'Donat', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 1.50 },
  { name: 'Hazelnut Cookies', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 1.50 },
  { name: 'Sweetball Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 2.00 },
  { name: 'Cinnamon Roll', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 2.00 },
  { name: 'Almond Croissant', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 2.20 },
  { name: 'Date Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 2.50 },
  { name: 'Toffy Delight', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 2.50 },
  { name: 'Basbusa', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Brownies', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Caramel', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Choco Mirror Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Coconut Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Cream Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Tramisu', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Black Forest Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Caramel Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Cheese Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Chocolate Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Mocha Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Red Velvet', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.00 },
  { name: 'Basbusa With Pastio', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.30 },
  { name: 'Lotus Cheese Cake', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 3.50 },
  { name: 'Plate Of Basbusa', category: 'Desserts', productCategory: 'Bakery & Desserts', price: 26.50 },
];

async function main() {
  console.log('Seeding database...');

  await prisma.menuItem.deleteMany();
  await prisma.stampEvent.deleteMany();
  await prisma.staff.deleteMany();

  await prisma.menuItem.createMany({
    data: menuItems.map(item => ({
      id: uuidv4(),
      name: item.name,
      category: item.category,
      productCategory: item.productCategory,
      price: item.price,
      imageUrl: pickImage(item.name, item.category),
      isAvailable: true,
    })),
  });
  console.log(`Seeded ${menuItems.length} menu items`);

  const adminHash = await bcrypt.hash('admin123', 12);
  const staffHash = await bcrypt.hash('staff123', 12);

  await prisma.staff.create({
    data: {
      id: uuidv4(),
      name: 'Admin',
      username: 'admin',
      passwordHash: adminHash,
      role: 'admin',
      isActive: true,
    },
  });

  await prisma.staff.create({
    data: {
      id: uuidv4(),
      name: 'Staff One',
      username: 'staff1',
      passwordHash: staffHash,
      role: 'staff',
      isActive: true,
    },
  });

  console.log('Seeded staff accounts (admin / staff1)');
  console.log('Done!');
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
